### ISSUE TITLE
New variables - START2030

### ISSUE THREAD

**Issue by ClaKet** [netzero2040/netzero2040#18]
Hi, for START2030 we would need the following additional variables:

- Energy and process related CO2 emissions|{Sector}
    - description: Energy and process related CO2 emissions by {Sector}
    - unit: MtCO2

- Wholesale electricity price
    -  description: Wholesale electricity price
    -  unit: €/MWh

- Employment
    - description: Employment
    - unit: 1,000 persons

To be discussed, whether also energy (gas, coal, oil) and carbon prices (price in EU ETS) that we use as inputs for the simulations should be added.

Thanks!

**Comment by zwiebo** [comment]
we can add also prices for other energy carriers

**Comment by danielhuppmann** [comment]
Two PRs implemented, the third request (prices) will be implemented later to prevent merge conflicts.
